Dev
n-leonovets/telegram_chats pull request #2
Opened 2023-12-23 20:13 UTC by n-leonovets

update code

2023-12-23 20:20 UTC, merged

2023-12-23 20:25 UTC, esemi requested changes

2023-12-23 20:25 UTC, esemi commented on config.py
я бы этот файл в src унёс, чего он наверху то?

2023-12-23 20:25 UTC, esemi commented on migrations/env.py
>          print("Таблицы созданы!")
принты лишние

2023-12-23 20:25 UTC, esemi commented on pyproject.toml
Имя проекта какое-то тестовое

2023-12-23 20:25 UTC, esemi commented on src/api/auth.py
> +    uow: UOWDep,
аще бесит что в каждом роуте ты это руками добавляешь

давай уж тогда автоматом везде пропишем, м?

2023-12-23 20:25 UTC, esemi commented on src/api/auth.py
> +    if not user_auth.is_admin:
а вот это можно сделать отдельной зависимостью, чтобы не писать какждый раз как раз

2023-12-23 20:25 UTC, esemi commented on src/api/category.py
> +            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
в чём смысл кидать пятисотку наружу?
Обычно кидают либо осмысленную ошибку либо "приложение и само упадёт"

2023-12-23 20:31 UTC, n-leonovets commented on src/api/category.py
> +            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
Не обработанную ошибку ты ведь хочешь записать в логи, чтобы потом было что исправлять, иначе как ты узнаешь об ошибке? А если есть try / except -- нужен raise HTTPException, чтобы вернуть фронту ошибку... Как без этого-то?

2023-12-23 20:33 UTC, n-leonovets commented on config.py
Миграции обращаются к config. Норм будет что миграции лезут в src?

2023-12-23 20:34 UTC, n-leonovets commented on migrations/env.py
>          print("Таблицы созданы!")
Не, это код для теста. Это же не миграции еще. Принт чисто для консоли, чтобы я видел что все норм

2023-12-23 20:35 UTC, n-leonovets commented on pyproject.toml
Косяк. Не должно было быть такого, я вроде меня его уже...

2023-12-23 20:41 UTC, n-leonovets commented on src/api/auth.py
> +    uow: UOWDep,
в смысле, а как? Ты ведь про `uow: UOWDep`? Его можно как-то для всех роутеров по умолчанию включить, не прописывая в самом роутере?

2023-12-23 20:44 UTC, n-leonovets commented on src/api/auth.py
> +    if not user_auth.is_admin:
Про что речь из 4 строк? Про `user_auth: UserPublic = Depends(required_auth)`? Типо сделать как с `uow: UOWDep`? 

По принципу:
`AuthDep = Annotated[UserPublic, Depends(required_auth)]`

И потом в роутерах:
`async def my_router(user_auth: AuthDep): ... `

Я правильно понял о чем речь?

2023-12-25 19:45 UTC, n-leonovets commented on src/api/auth.py
> +    uow: UOWDep,
Изучил. Если засунуть` uow: UOWDep` в глобальный Depends -- ты не сможешь его получить далее в функции, а его ведь нужно передать для соединения с БД... 

Пример:
```
app = FastAPI(dependencies=[Depends(UOWDep)])
router = APIRouter(prefix="/chats", tags=["Chats"])

@router.post("/chat/")
async def add_chat(
    chat: ChatAdd,
    user_auth: AuthDep
) -> ChatResponse:
        return await ChatService().add_chat(uow=**???**, chat=chat) # Что мы передаем в uow?
```